const image = {
    banner_img_1: require('./home/banner_img_1.png'),
    banner_img_2: require('./home/banner_img_2.png'),
    banner_img_3: require('./home/banner_img_3.png'),
    banner_img_4: require('./home/banner_img_4.png'),
    banner_img_5: require('./home/banner_img_5.png'),
    blog_img_1: require('./blog/img_1.png'),
    blog_img_2: require('./blog/img_2.png'),
    blog_img_3: require('./blog/img_3.png'),
    blog_img_4: require('./blog/img_4.png'),
    blog_img_5: require('./blog/img_5.png'),
    blog_img_6: require('./blog/img_6.png'),
    blog_img_7: require('./blog/img_7.png'),
    blog_img_8: require('./blog/img_8.png'),
    blog_img_9: require('./blog/img_9.png'),
    blog_img_10: require('./blog/img_10.png'),
    blog_img_11: require('./blog/img_11.png'),
    blog_img_12: require('./blog/img_12.png'),

    post_img_1: require('./post/img_1.png'),
    post_img_2: require('./post/img_2.png'),
    service_img_1: require('./service/img_1.png'),
    service_img_2: require('./service/img_2.png'),
    service_img_3: require('./service/img_3.png'),
    document_img_1: require('./document/document_1.png'),
    document_img_2: require('./document/document_2.png'),
    document_img_3: require('./document/document_3.png'),
    document_img_4: require('./document/document_4.png'),
    document_img_5: require('./document/document_5.png'),
    document_img_6: require('./document/document_6.png'),
    document_img_7: require('./document/document_7.png'),
    document_img_8: require('./document/document_8.png')
};

export default image;
